config/routes.rb
Rails.application.routes.draw do
  resources :quick_codes

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/quick_code.rb
class QuickCode < ActiveRecord::Base
  belongs_to :user

  validates :name, :presence => true, length: { in: 3..20 }
  validates :content, :presence => true, length: { in: 1..50 }
  validates :size, :presence => true, length: { in: 2..4 }, numericality: { only_integer: true }
  validates :offset, :presence => true, length: { in: 1..10 }, numericality: { only_integer: true }
  validates :unit, :presence => true, length: { in: 1..10 }, numericality: { only_integer: true }
  validates :fill, :css_hex_color => true, :presence => true
  validates :color, :css_hex_color => true, :presence => true
  validate :qr_count_within_limit, :on => :create

  def qr_count_within_limit
    if self.user.quick_codes(:reload).count >= 10
      errors.add(:base, "Exceeded QR Code limit. Delete old QR Codes for more room.")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quick_codes
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quick_codes_controller.rb
class QuickCodesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_quick_code, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @quick_codes = current_user.quick_codes.all

    respond_to do |format|
      format.html
      # Provide an XLS or CSV list
      format.xls { send_data(@quick_codes.to_xls, :filename => "Codes-#{Time.now.strftime("%Y%m%d%H%M%S")}.xls") }
      format.csv { send_data(@quick_codes.to_csv, :filename => "Codes-#{Time.now.strftime("%Y%m%d%H%M%S")}.csv") }
    end
  end

  def show
    fill = @quick_code.fill[1..-1]
    color = @quick_code.color[1..-1]

    respond_to do |format|
      format.html
      # Render the QR Code images
      format.svg  { render :qrcode => @quick_code.content, :level => :h, :unit => @quick_code.unit, :offset => @quick_code.offset, :fill => fill, :color => color }
      format.png  { render :qrcode => @quick_code.content, :level => :h, :unit => @quick_code.unit, :offset => @quick_code.offset, :fill => fill, :color => color }
      format.gif  { render :qrcode => @quick_code.content, :level => :h, :unit => @quick_code.unit, :offset => @quick_code.offset, :fill => fill, :color => color }
      format.jpg  { render :qrcode => @quick_code.content, :level => :h, :unit => @quick_code.unit, :offset => @quick_code.offset, :fill => fill, :color => color }
    end
  end

  def new
    @quick_code = current_user.quick_codes.new
    respond_with(@quick_code)
  end

  def edit
  end

  def create
    @quick_code = current_user.quick_codes.new(quick_code_params)
    flash[:notice] = 'QuickCode was successfully created.' if @quick_code.save
    respond_with(@quick_code)
  end

  def update
    flash[:notice] = 'QuickCode was successfully updated.' if @quick_code.update(quick_code_params)
    respond_with(@quick_code)
  end

  def destroy
    @quick_code.destroy
    respond_with(@quick_code)
  end

  private
    def set_quick_code
      @quick_code = current_user.quick_codes.find(params[:id])
    end

    def quick_code_params
      params.require(:quick_code).permit(:name, :content, :size, :level, :offset, :unit, :fill, :color)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quick_codes_helper.rb
module QuickCodesHelper
end

app/views/layouts/_favicons.html.haml
%link{:href => "apple-touch-icon-57x57.png", :rel => "apple-touch-icon-precomposed", :sizes => "57x57"}/
%link{:href => "apple-touch-icon-114x114.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}/
%link{:href => "apple-touch-icon-72x72.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}/
%link{:href => "apple-touch-icon-144x144.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}/
%link{:href => "apple-touch-icon-60x60.png", :rel => "apple-touch-icon-precomposed", :sizes => "60x60"}/
%link{:href => "apple-touch-icon-120x120.png", :rel => "apple-touch-icon-precomposed", :sizes => "120x120"}/
%link{:href => "apple-touch-icon-76x76.png", :rel => "apple-touch-icon-precomposed", :sizes => "76x76"}/
%link{:href => "apple-touch-icon-152x152.png", :rel => "apple-touch-icon-precomposed", :sizes => "152x152"}/
%link{:href => "favicon-196x196.png", :rel => "icon", :sizes => "196x196", :type => "image/png"}/
%link{:href => "favicon-96x96.png", :rel => "icon", :sizes => "96x96", :type => "image/png"}/
%link{:href => "favicon-32x32.png", :rel => "icon", :sizes => "32x32", :type => "image/png"}/
%link{:href => "favicon-16x16.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
%link{:href => "favicon-128.png", :rel => "icon", :sizes => "128x128", :type => "image/png"}/
%meta{:content => " ", :name => "application-name"}/
%meta{:content => "#FFFFFF", :name => "msapplication-TileColor"}/
%meta{:content => "mstile-144x144.png", :name => "msapplication-TileImage"}/
%meta{:content => "mstile-70x70.png", :name => "msapplication-square70x70logo"}/
%meta{:content => "mstile-150x150.png", :name => "msapplication-square150x150logo"}/
%meta{:content => "mstile-310x150.png", :name => "msapplication-wide310x150logo"}/
%meta{:content => "mstile-310x310.png", :name => "msapplication-square310x310logo"}/

app/views/layouts/_footer.html.haml
%footer.text-center
  MIT License | View this project on
  %a{:href => "http://github.com/astorrer/QRquick"}
    %strong Github

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
#top-nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-toggle
      = link_to 'QRquick', root_path, class: 'navbar-brand'
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - unless user_signed_in?
          %li= link_to 'Sign in', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
              %i.glyphicon.glyphicon-user
              = current_user.email
              %span.caret
            %ul#g-account-menu.dropdown-menu{:role => "menu"}
              %li
                = link_to edit_user_registration_path do
                  %i.glyphicon.glyphicon-wrench
                  Settings
              %li
                = link_to destroy_user_session_path, :method=>'delete' do
                  %i.glyphicon.glyphicon-lock
                  Logout

app/views/layouts/_sidebar.html.haml
.row
  .col-sm-2
    %hr/
    %ul.nav.nav-stacked
      %li
        = link_to quick_codes_path do
          %i.glyphicon.glyphicon-list-alt
          MANAGE
      %li
        = link_to new_quick_code_path do
          %i.glyphicon.glyphicon-qrcode
          ADD CODE
      %li
        = link_to quick_codes_path(@quick_codes, format: "xls") do
          %i.glyphicon.glyphicon-export
          EXPORT XLS
      %li
        = link_to quick_codes_path(@quick_codes, format: "csv") do
          %i.glyphicon.glyphicon-export
          EXPORT CSV
  .col-sm-10
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'QRquick'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'QRquick'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = render 'layouts/favicons'
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .container
      - if user_signed_in?
        = render 'layouts/sidebar'
      - else
        .row
          .col-sm-12
            = render 'layouts/messages'
            = yield

    = render 'layouts/footer'

app/views/quick_codes/_form.html.haml
.row
  .col-lg-12
    - if @quick_code.errors.any?
      .alert.alert-warning.alert-dismissable
        %a.close{:'data-dismiss' => "alert", :href => '#'} &times;
        %i.fa.fa-exclamation-sign
        = pluralize(@quick_code.errors.count, "error") + ' prevented this area from being created:'
        %ul
          - @quick_code.errors.full_messages.each do |msg|
            %li= msg

.row
  .col-lg-8.col-lg-offset-2
    .well.bs-component
      = form_for(@quick_code, class: 'form-horizontal') do |f|
        %fieldset
          %legend QR Code
          .form-group
            .row
              .col-lg-2
                = f.label :name, class: 'col-lg-2 control-label'
              .col-lg-10
                = f.text_field :name, class: "form-control"
          .form-group
            .row
              .col-lg-2
                = f.label :content, class: 'col-lg-2 control-label'
              .col-lg-10
                = f.text_field :content, class: "form-control"
                %span.help-block Specify the content (URL, Phone, etc.) of the code.
          .form-group
            .row
              .col-lg-2
                = f.label :size, class: 'col-lg-2 control-label'
              .col-lg-10
                = f.number_field :size, class: "form-control"
                %span.help-block Specify the size (resolution) of the code.
          .form-group
            .row
              .col-lg-2
                = f.label :offset, class: 'col-lg-2 control-label'
              .col-lg-10
                = f.number_field :offset, class: "form-control"
                %span.help-block Specify the offset of the code. (Try 10) 
          .form-group
            .row
              .col-lg-2
                = f.label :unit, class: 'col-lg-2 control-label'
              .col-lg-10
                = f.number_field :unit, class: "form-control"
                %span.help-block Specify the offset of the code.(Try 11) 
          .form-group
            .row
              .col-lg-2
                = f.label :fill, class: 'col-lg-2 control-label'
              .col-lg-10
                = f.text_field :fill, class: "form-control"
                %span.help-block Tip: Pick colors that contrast strongly. 
          .form-group
            .row
              .col-lg-2
                = f.label :color, class: 'col-lg-2 control-label'
              .col-lg-10
                = f.text_field :color, class: "form-control"
                %span.help-block Specify the color of the code.
          .form-group
            .col-lg-10.col-lg-offset-2
              = f.button :submit, class: 'btn btn-default'

app/views/quick_codes/edit.html.haml
= render 'form'

app/views/quick_codes/index.html.haml
%h1 QR Codes

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Content
      %th Download
      %th 
  %tbody
    - @quick_codes.each do |quick_code|
      %tr
        %td.col-lg-1.col-md-1.col-sm-1= quick_code.name
        %td.col-lg-6.col-md-4.col-sm-4= quick_code.content
        %td.col-lg-3.col-md-2.col-sm-2
          .btn-group
            = link_to "SVG", quick_code_path(quick_code, format: "svg"), class: 'btn btn-primary'
            = link_to "PNG", quick_code_path(quick_code, format: "png"), class: 'btn btn-primary'
            = link_to "GIF", quick_code_path(quick_code, format: "gif"), class: 'btn btn-primary'
            = link_to "JPG", quick_code_path(quick_code, format: "jpg"), class: 'btn btn-primary'
        %td.col-lg-2.col-md-2.col-sm-2
          .btn-group
            = link_to quick_code, class: 'btn btn-default' do
              %i.glyphicon.glyphicon-eye-open
            = link_to edit_quick_code_path(quick_code), class: 'btn btn-default' do
              %i.glyphicon.glyphicon-edit
            = link_to quick_code, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger' do
              %i.glyphicon.glyphicon-trash

app/views/quick_codes/new.html.haml
= render 'form'

app/views/quick_codes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @quick_code.name
%p
  %b Content:
  = @quick_code.content
%p
  %b Size:
  = @quick_code.size
%p
  %b Level:
  = @quick_code.level
%p
  %b Offset:
  = @quick_code.offset
%p
  %b Unit:
  = @quick_code.unit
%p
  %b Fill:
  = @quick_code.fill
%p
  %b Color:
  = @quick_code.color

= link_to 'Edit', edit_quick_code_path(@quick_code)
\|
= link_to 'Back', quick_codes_path

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.haml
.container-fluid
  .row
    .col-lg-12
      = image_tag('logo.png', class: 'image-responsive', style: 'height: 200px' )
      %hr
  .row
    .col-lg-6
      %h3 Welcome
      %p
        QRquick is an open source QR Code generator application. Use it for business cards, T-Shirts, 
        photos, and more! Store up to ten codes in our database, for free!
      %h4 How do I read the codes?
      %p
        You can read them with a scanner or built in camera. You may need to download an app, 
        but don't worry- there are tons of free apps for both Android and IOS.
    .col-lg-6
      %h3 Features
      %ul
        %li Open Source
        %li Store Hundreds of Codes
        %li Custom Colors
        %li CSV & EXCEL Export
        %li Download as an SVG, GIF, PNG, or JPG.
        %li 10 Free Codes!
      %hr
      %a{:href => "http://www.beyondsecurity.com/vulnerability-scanner-verification/www.qrquick.rocks"}
        %img{:alt => "Website Security Test", :border => "0", :src => "https://secure.beyondsecurity.com/verification-images/www.qrquick.rocks/vulnerability-scanner-2.gif"}/
  .row
    .col-lg-12
      %h6 “QR Code” is registered trademark of DENSO WAVE INCORPORATED